#!/usr/bin/env python
# -*- coding: utf-8 -*-

theses = [
    (u"Aynetchi, Alyar", u"AlyarAynetchi_Site"),
    (u"Bossink, Annelot", u"AnnelotBossink"),
    (u"Bruijn, Menno de", u"mennodebruijn"),
    (u"Chan, Melissa", u"MelissaChan"),
    (u"Costa, Inês da", u"Thesis_Ines"),
    (u"Couvert, Nina", u"Nina_Thesis"),
    (u"Dam, Ditmar van", u"DitmarVanDam_Scriptie"),
    (u"Douma, Rosa", u"rozel"),
    (u"Gottlieb, Marius", u"Marius-Thesis"),
    (u"Gragt, Reni van der", u"renivandergragt"),
    (u"Groenendaal, Sanne", u"SanneGroenendaal"),
    (u"Hendriksma, Lennart", u"Lennart_Thisis"),
    (u"Kokken, Mike", u"ScriptieReaderMikeKokken"),
    (u"Komen, Tomas", u"tomaskomen"),
    (u"Kooten, Mirte van", u"MirtevanKooten_Thesis"),
    (u"Laar, Tomas", u"Tomas_Laar_Thesis"),
    (u"Leliveld, Danicha", u"danicha-scriptie"),
    (u"Lennarts, Max", u"MaxLennarts"),
    (u"Liaudanskaitė, Viktorija", u"Viktorija"),
    (u"Lith, Julian van", u"julian_thesis"),
    (u"Louter, René", u"ReneLouter-Thesis"),
    (u"Mickuté, Monika", u"MonikaM"),
    (u"Modder, Ilse", u"ilsemodder"),
    (u"Monen, Wilco", u"wilcomonen"),
    (u"Mulder, Alice", u"alicemulderthesis"),
    (u"Neppelenbroek, Sophie", u"SophieNeppelenbroek"),
    (u"Noordmans, Sep", u"SepNoordmans-thesis"),
    (u"Ploeg, Eline van der", u"Eline"),
    (u"Pöll, Regina", u"ReginaPoell"),
    (u"Puhl, Sander", u"sanderpuhl"),
    (u"Remundt, Tim van", u"Customisable_Design"),
    (u"Risvåg, Sara", u"Sara_Therese_Thesis"),
    (u"Rovers, Jordie", u"Jordie_Thesis"),
    (u"Rullerova, Tereza", u"Tereza_Thesis"),
    (u"Salo, Irene", u"Irene_Thesis"),
    (u"Savisaar, Edgar", u"edgar"),
    (u"Schepen, Marcel", u"Marcel_Schepen_Thesis"),
    (u"Stoop, Machteld", u"MachteldStoop"),
    (u"Tan-A-Kiam, Orphé", u"OrpheTana"),
    (u"Terlouw, Janine", u"JanineThesis"),
    (u"Timmerman, Sandra", u"Experimenteren-met-oude-gewoontes-1"),
    (u"Valule, Ieva", u"ieva"),
    (u"Velyaminov, Fedor", u"fedor.velyaminov"),
    (u"West, Donna van", u"donnathesis"),
]

